### ISSUE TITLE
have a problem when load_caffe_weights.py

### ISSUE THREAD

**Issue by batigooal** [chuanqi305/MobileNetv2-SSDLite#2]
No such file or directory: 'output/Conv_biases.dat'

**Comment by hemuwei** [comment]
I meet the same problem "No such file or directory: 'output/Conv_biases.dat'"

**Comment by HAN-Seul** [comment]
you could try to create a  new folder called  'output ' in  the current  directory

**Comment by chuanqi305** [comment]
@batigooal @hemuwei Issue solved.

**Comment by itemhsu** [comment]
I have the same problem. The file "Conv_biases.dat" will not be created with the dump_tensorflow_weights.py command. This file dose not exist so you will get the "No such file or directory: 'output/Conv_biases.dat'" error. I think the error is at line 30,31 of  load_caffe_weights.py.

**Comment by Duankaiwwen** [comment]
@chuanqi305 I still meet this problem, how do you sloved
