### ISSUE TITLE
result box has offset for ssdlite_mobilenet_v2_coco net 

### ISSUE THREAD

**Issue by tianylijun** [chuanqi305/MobileNetv2-SSDLite#34]
i convert ssdlite_mobilenet_v2_coco_2018_05_09 model from tensorflow to caffe, the result boxs get from caffe (I use your ssd caffe with relu6 version) all have some offset, any suggest about the issuse?

![ssd-3](https://user-images.githubusercontent.com/23356740/46866880-b04a4700-ce55-11e8-86b8-fd6a5d4d6186.jpg)
![ssd-2](https://user-images.githubusercontent.com/23356740/46866882-b0e2dd80-ce55-11e8-9f52-8087e82483e2.jpg)
![ssd-1](https://user-images.githubusercontent.com/23356740/46866883-b0e2dd80-ce55-11e8-9fd2-aeb247cd371c.jpg)

I get there is has_tf_pad in base_conv_layer.cpp, how to add this param into prototxt?????

**Comment by chuanqi305** [comment]
@tianylijun Make sure use ReLU6 to replace ReLU

**Comment by tianylijun** [comment]
I have fix it

**Comment by runauto** [comment]
@tianylijun how to fix it ?i meet  the same error as you.
