### ISSUE TITLE
No max_size for the conv_13/expand related prior box?

### ISSUE THREAD

**Issue by d-li14** [chuanqi305/MobileNetv2-SSDLite#35]
@chuanqi305 Thanks for your Caffe implementation. 
I'm confused that in terms of the `PriorBox` layer relevant to `conv_13/expand`, there is only min_size=60, without max_size. Would you please explain why this setting is omitted? Thanks in advance.

**Comment by chuanqi305** [comment]
@d-li14 the anchors of conv_13/expand is  [(0.2, 1.0), (0.2, 2.0), (0.2, 0.5)],
 0.2 = 60 / 300
1.0，2.0，0.5 is the aspect ratios.
Anchor number of the other layers is 6, that is:
min_size, aspect_ratio(1.0, 2.0, 0.5)
max_size, aspect_ratio(1.0, 2.0, 0.5)

**Comment by chuanqi305** [comment]
@d-li14 right.

**Comment by d-li14** [comment]
OK, thanks for your explanation. @chuanqi305 
BTW, I'm interested in the script `show_tensor.py` that you mentioned in #1 , but haven't got what it is even after searching. Could you give some hint about that?
