### ISSUE TITLE
Check failed: target_blobs.size() == source_layer.blobs_size() (1 vs. 2) Incompatible number of blobs for layer Conv

### ISSUE THREAD

**Issue by youngxiao** [chuanqi305/MobileNetv2-SSDLite#41]
I used gen_model.py to generate train.prototxt. However, when training MobileNetv2-SSDLite, this issue arised.
```
I1213 14:58:07.939759 21634 net.cpp:761] Ignoring source layer input
I1213 14:58:07.939764 21634 net.cpp:761] Ignoring source layer data_input_0_split
F1213 14:58:07.939779 21634 net.cpp:767] Check failed: target_blobs.size() == source_layer.blobs_size() (1 vs. 2) Incompatible number of blobs for layer Conv
*** Check failure stack trace: ***
```

**Comment by youngxiao** [comment]
fixed.

**Comment by gongdalinux** [comment]
> fixed.

I meet the same problem. How to fix? TKS

**Comment by gongdalinux** [comment]
> I used gen_model.py to generate train.prototxt. However, when training MobileNetv2-SSDLite, this issue arised.
> 
> ```
> I1213 14:58:07.939759 21634 net.cpp:761] Ignoring source layer input
> I1213 14:58:07.939764 21634 net.cpp:761] Ignoring source layer data_input_0_split
> F1213 14:58:07.939779 21634 net.cpp:767] Check failed: target_blobs.size() == source_layer.blobs_size() (1 vs. 2) Incompatible number of blobs for layer Conv
> *** Check failure stack trace: ***
> ```

I meet the same problem. How to fix? TKS

**Comment by youngxiao** [comment]
@gongdalinux try this [gen_model.py](https://github.com/youngxiao/MobileNetv2-SSDLite/blob/master/ssdlite/gen_model.py)

**Comment by gongdalinux** [comment]
> @gongdalinux try this [gen_model.py](https://github.com/youngxiao/MobileNetv2-SSDLite/blob/master/ssdlite/gen_model.py)

I tried your gen_model.py. But got the issue:
F0117 21:34:50.957195  1386 multibox_loss_layer.cpp:141] Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (44091 vs. 41925) Number of priors must match number of confidence predictions.
*** Check failure stack trace: ***
    @     0x7f11efa7d5cd  google::LogMessage::Fail()
    @     0x7f11efa7f433  google::LogMessage::SendToLog()
    @     0x7f11efa7d15b  google::LogMessage::Flush()
    @     0x7f11efa7fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f11f0323a02  caffe::MultiBoxLossLayer<>::Reshape()
    @     0x7f11f0388933  caffe::Net<>::Init()
    @     0x7f11f038a161  caffe::Net<>::Net()
    @     0x7f11f01be78a  caffe::Solver<>::InitTrainNet()
    @     0x7f11f01bfa87  caffe::Solver<>::Init()
    @     0x7f11f01bfe2a  caffe::Solver<>::Solver()
    @     0x7f11f03a88e9  caffe::Creator_RMSPropSolver<>()
    @           0x40afd9  train()
    @           0x4077e8  main
    @     0x7f11ee213830  __libc_start_main
    @           0x4080b9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
Do you know how to fix it?
TKS~

**Comment by gongdalinux** [comment]
> @gongdalinux try this [gen_model.py](https://github.com/youngxiao/MobileNetv2-SSDLite/blob/master/ssdlite/gen_model.py)

I tried your gen_model.py. But got the issue:
F0117 21:34:50.957195  1386 multibox_loss_layer.cpp:141] Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (44091 vs. 41925) Number of priors must match number of confidence predictions.
*** Check failure stack trace: ***
    @     0x7f11efa7d5cd  google::LogMessage::Fail()
    @     0x7f11efa7f433  google::LogMessage::SendToLog()
    @     0x7f11efa7d15b  google::LogMessage::Flush()
    @     0x7f11efa7fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f11f0323a02  caffe::MultiBoxLossLayer<>::Reshape()
    @     0x7f11f0388933  caffe::Net<>::Init()
    @     0x7f11f038a161  caffe::Net<>::Net()
    @     0x7f11f01be78a  caffe::Solver<>::InitTrainNet()
    @     0x7f11f01bfa87  caffe::Solver<>::Init()
    @     0x7f11f01bfe2a  caffe::Solver<>::Solver()
    @     0x7f11f03a88e9  caffe::Creator_RMSPropSolver<>()
    @           0x40afd9  train()
    @           0x4077e8  main
    @     0x7f11ee213830  __libc_start_main
    @           0x4080b9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
Do you know how to fix it?
TKS~

**Comment by youngxiao** [comment]
@gongdalinux I guess you used a pre-trained model for training. Your train.prototxt may not match the parameters in the pre-trained model .caffemodel (mainly the number of classes does not match). The solutions are:

solution 1. training without pre-trained model. 

solution 2. get TF MobileNetv2-SSDLite(COCO), convert the tf model to caffe, then modify coco2voc.py according to the correct number of your classes. `python coco2voc.py` can generate new pre-trained caffemodel corresponding to the number of your classes.
step:
get TF COCO model
```
cd MobileNetv2-SSDLite/ssdlite/
wget http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz
tar -zvxf ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz

```
convert TF model to caffe
```
python dump_tensorflow_weights.py
python load_caffe_weight.py  
```

modify coco2voc.py with the correct number of your classes, then the following script generate the new caffemodel which can be used as a pre-trained model.
```
python coco2voc.py
```

**Comment by gongdalinux** [comment]
@youngxiao Modify coco2voc.py? I have read coco2voc.py, but have no ideas to modify. Modify maps?
Btw,  I changed layer names(conv_13/expand_mbox_conf', 'Conv_1_mbox_conf', 'layer_19_2_2_mbox_conf', 'layer_19_2_3_mbox_conf', 'layer_19_2_4_mbox_conf', 'layer_19_2_5_mbox_conf') to train.But training loss is always about 7~9.It can't drop.Do you know teh reason?

I0118 15:55:54.816042  7953 sgd_solver.cpp:138] Iteration 81910, lr = 2.5e-06
I0118 15:55:56.483775  7953 solver.cpp:243] Iteration 81920, loss = 8.27985
I0118 15:55:56.483814  7953 solver.cpp:259]     Train net output #0: mbox_loss = 6.54045 (* 1 = 6.54045 loss)
I0118 15:55:56.483824  7953 sgd_solver.cpp:138] Iteration 81920, lr = 2.5e-06
I0118 15:55:58.156587  7953 solver.cpp:243] Iteration 81930, loss = 8.10207
I0118 15:55:58.156627  7953 solver.cpp:259]     Train net output #0: mbox_loss = 7.92256 (* 1 = 7.92256 loss)
I0118 15:55:58.156635  7953 sgd_solver.cpp:138] Iteration 81930, lr = 2.5e-06
I0118 15:55:59.822367  7953 solver.cpp:243] Iteration 81940, loss = 7.50622
I0118 15:55:59.822401  7953 solver.cpp:259]     Train net output #0: mbox_loss = 6.26264 (* 1 = 6.26264 loss)
I0118 15:55:59.822407  7953 sgd_solver.cpp:138] Iteration 81940, lr = 2.5e-06
I0118 15:56:01.490677  7953 solver.cpp:243] Iteration 81950, loss = 9.10947
I0118 15:56:01.490721  7953 solver.cpp:259]     Train net output #0: mbox_loss = 13.3048 (* 1 = 13.3048 loss)
I0118 15:56:01.490730  7953 sgd_solver.cpp:138] Iteration 81950, lr = 2.5e-06
I0118 15:56:03.150979  7953 solver.cpp:243] Iteration 81960, loss = 9.44784
I0118 15:56:03.151013  7953 solver.cpp:259]     Train net output #0: mbox_loss = 6.27952 (* 1 = 6.27952 loss)

**Comment by youngxiao** [comment]
@gongdalinux 
My trianing loss is about 3, when 100000 Iteration with batchsize 32.
If you want to train with a pre-trained model, you need to modify `coco2voc.py`. It can convert caffe coco model to your model. For example, you have 2 classes. The `load_net()` function can be modified like this:
```python
def load_net(net, net2):
    #maps = [0,5,2,15,9,40,6,3,16,57,20,61,17,18,4,1,59,19,58,7,63]
    maps = [0,1,2]   # 0 -- background
    for key in net.params.iterkeys():
        if type(net.params[key]) is not caffe._caffe.BlobVec:
            break
        else:
            if key.endswith('mbox_conf'):
                for i in range(len(net.params[key])):
                    wt = net.params[key][i].data
                    x = wt.shape[0] / 91
                    wt = wt.reshape(x, 91, -1)
                    neww = np.ones((x, 3, wt.shape[2])) # 2 classes  + 1
                    print(neww.shape)
                    print(wt.shape)
                    for j,m in enumerate(maps):
                       neww[:,j,:] = wt[:,m,:]
                    net2.params[key][i].data[...] = neww.reshape(net2.params[key][i].data.shape)
                print(key)
            else:
                for i in range(len(net.params[key])):
net2.params[key][i].data[...] = net.params[key][i].data
```

**Comment by gongdalinux** [comment]
@youngxiao I have 12 classes. I modify The load_net() function like this:

def load_net(net, net2):
    #maps = [0,5,2,15,9,40,6,3,16,57,20,61,17,18,4,1,59,19,58,7,63]
    #maps = [0,5,2,16,9,44,6,3,17,62,21,67,18,19,4,1,64,20,63,7,72]
    maps = [0,1,2,3,4,5,6,7,8,9,10,11]
    for key in net.params.iterkeys():
        if type(net.params[key]) is not caffe._caffe.BlobVec:
            break
        else:
            if key.endswith('mbox_conf'):
                print(key)
                print(len(net.params[key]))
                for i in range(len(net.params[key])):
                    wt = net.params[key][i].data
                    print(wt.shape)
                    x = wt.shape[0] / 91
                    wt = wt.reshape(x, 91, -1)
                    #neww = np.ones((x, 21, wt.shape[2]))
                    neww = np.ones((x, 12, wt.shape[2]))
                    print(neww.shape)       #(3, 12, 576)
                    for j,m in enumerate(maps):
                       neww[:,j,:] = wt[:,m,:]
                   print(net2.params[key][i].data.shape)      #(63, 576, 1, 1)
                    net2.params[key][i].data[...] = neww.reshape(net2.params[key][i].data.shape)
            print(key)
            else:
                for i in range(len(net.params[key])):
                    net2.params[key][i].data[...] = net.params[key][i].data

but got an error:
I0125 11:33:45.636862 27527 net.cpp:270] This network produces output mbox_loc
I0125 11:33:45.636867 27527 net.cpp:270] This network produces output mbox_priorbox
I0125 11:33:45.637001 27527 net.cpp:283] Network initialization done.
conv_13/expand_mbox_conf
2
(273, 576, 1, 1)
(3, 12, 576)
(3, 91, 576)
(63, 576, 1, 1)
Traceback (most recent call last):
  File "coco2voc.py", line 48, in <module>
    load_net(net, net2)
  File "coco2voc.py", line 33, in load_net
    net2.params[key][i].data[...] = neww.reshape(net2.params[key][i].data.shape)
ValueError: cannot reshape array of size 20736 into shape (63,576,1,1)

How to fix? And maps = [0,1,2,3,4,5,6,7,8,9,10,11] is correct? I  do not know how modify maps. 
Thanks very much!

**Comment by youngxiao** [comment]
@gongdalinux 12 classes，if your categories are also in coco, the best way is to use the coco label_id in `maps`.
For example, your class order is 
```
[cat, dog, bird, fish, chicken, deer, leopard, tiger, lion, dolphin， shark, horse ]
```
`[cat, dog, bird, horse] `are also in COCO datasets. 
In COCO, `[bird-16,  cat-17,  dog-18,  horse-19]`.
Then `maps` should be:  
```
maps = [0, 17, 18, 16,  4,  5,  6,  7,  8,  9,  10,  11, 19]
```
because 0 -- background. The other category (not in COCO) ids can be given casually.
BTW,  `neww = np.ones((x, 12, wt.shape[2]))` should be `neww = np.ones((x, 13, wt.shape[2]))`

**Comment by weilanShi** [comment]
> > @gongdalinux try this [gen_model.py](https://github.com/youngxiao/MobileNetv2-SSDLite/blob/master/ssdlite/gen_model.py)
> 
> I tried your gen_model.py. But got the issue:
> F0117 21:34:50.957195 1386 multibox_loss_layer.cpp:141] Check failed: num_priors_ * num_classes_ == bottom[1]->channels() (44091 vs. 41925) Number of priors must match number of confidence predictions.
> *** Check failure stack trace: ***
> @ 0x7f11efa7d5cd google::LogMessage::Fail()
> @ 0x7f11efa7f433 google::LogMessage::SendToLog()
> @ 0x7f11efa7d15b google::LogMessage::Flush()
> @ 0x7f11efa7fe1e google::LogMessageFatal::~LogMessageFatal() @ 0x7f11f0323a02 caffe::MultiBoxLossLayer<>::Reshape() @ 0x7f11f0388933 caffe::Net<>::Init() @ 0x7f11f038a161 caffe::Net<>::Net() @ 0x7f11f01be78a caffe::Solver<>::InitTrainNet() @ 0x7f11f01bfa87 caffe::Solver<>::Init() @ 0x7f11f01bfe2a caffe::Solver<>::Solver() @ 0x7f11f03a88e9 caffe::Creator_RMSPropSolver<>() @ 0x40afd9 train() @ 0x4077e8 main @ 0x7f11ee213830 __libc_start_main @ 0x4080b9 _start @ (nil) (unknown) Aborted (core dumped) Do you know how to fix it? TKS~


It works，thanks
